// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from data.proto</summary>
public static partial class DataReflection {

  #region Descriptor
  /// <summary>File descriptor for data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgpkYXRhLnByb3RvIs0CCgREYXRhEhIKCHJvb21OYW1lGAEgASgJSAASEgoI",
          "cG9zaXRpb24YAiABKAVIABIVCgtEaXNwbGF5TmFtZRgDIAEoCUgAEhEKB21l",
          "c3NhZ2UYBCABKAlIABITCgluZXdVc2VySUQYBSABKAlIABIXCgVldmVudBgH",
          "IAEoDjIGLkV2ZW50SAASIQoKb3Rvc2hpZGFtYRgIIAEoCzILLk90b3NoaWRh",
          "bWFIABIdCghyb3VsZXR0ZRgLIAEoCzIJLlJvdWxldHRlSAASGQoGc3BhY2Vz",
          "GAkgASgLMgcuU3BhY2VzSAASGQoPb3Rvc2hpZGFtYVRvdGFsGAwgASgFSAAS",
          "FQoEcXVpehgNIAEoCzIFLlF1aXpIABIOCgZ1c2VySUQYBiABKAkSEwoGcmVz",
          "dWx0GAogASgJSAGIAQFCBgoEdHlwZUIJCgdfcmVzdWx0IiAKBlNwYWNlcxIW",
          "CgZzcGFjZXMYASADKA4yBi5TcGFjZSIsCgpPdG9zaGlkYW1hEg4KBnVzZXJJ",
          "RBgBIAEoCRIOCgZhbW91bnQYAiABKAUiKgoIUm91bGV0dGUSDgoGdXNlcklE",
          "GAEgASgJEg4KBm51bWJlchgCIAEoBSI5CgRRdWl6EhAKCHF1ZXN0aW9uGAEg",
          "ASgJEg8KB2Nob2ljZXMYAiADKAkSDgoGYW5zd2VyGAMgASgFKlMKBUV2ZW50",
          "EgwKCFJPVUxFVFRFEAASDgoKT1RPU0hJREFNQRABEg0KCUZVUklEQVNISRAC",
          "EggKBEpPSU4QAxIJCgVMRUFWRRAEEggKBFFVSVoQBSp3CgVTcGFjZRIPCgtT",
          "VEFSVF9TUEFDRRAAEg4KCkdPQUxfU1BBQ0UQARIUChBPVE9TSElEQU1BX1NQ",
          "QUNFEAISEgoOUk9VTEVUVEVfU1BBQ0UQAxITCg9GVVJJREFTSElfU1BBQ0UQ",
          "BBIOCgpRVUlaX1NQQUNFEAViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Event), typeof(global::Space), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Data), global::Data.Parser, new[]{ "RoomName", "Position", "DisplayName", "Message", "NewUserID", "Event", "Otoshidama", "Roulette", "Spaces", "OtoshidamaTotal", "Quiz", "UserID", "Result" }, new[]{ "Type", "Result" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Spaces), global::Spaces.Parser, new[]{ "Spaces_" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Otoshidama), global::Otoshidama.Parser, new[]{ "UserID", "Amount" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Roulette), global::Roulette.Parser, new[]{ "UserID", "Number" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Quiz), global::Quiz.Parser, new[]{ "Question", "Choices", "Answer" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum Event {
  [pbr::OriginalName("ROULETTE")] Roulette = 0,
  [pbr::OriginalName("OTOSHIDAMA")] Otoshidama = 1,
  [pbr::OriginalName("FURIDASHI")] Furidashi = 2,
  [pbr::OriginalName("JOIN")] Join = 3,
  [pbr::OriginalName("LEAVE")] Leave = 4,
  [pbr::OriginalName("QUIZ")] Quiz = 5,
}

public enum Space {
  [pbr::OriginalName("START_SPACE")] StartSpace = 0,
  [pbr::OriginalName("GOAL_SPACE")] GoalSpace = 1,
  [pbr::OriginalName("OTOSHIDAMA_SPACE")] OtoshidamaSpace = 2,
  [pbr::OriginalName("ROULETTE_SPACE")] RouletteSpace = 3,
  [pbr::OriginalName("FURIDASHI_SPACE")] FuridashiSpace = 4,
  [pbr::OriginalName("QUIZ_SPACE")] QuizSpace = 5,
}

#endregion

#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Data : pb::IMessage<Data>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Data> _parser = new pb::MessageParser<Data>(() => new Data());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Data> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Data() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Data(Data other) : this() {
    userID_ = other.userID_;
    result_ = other.result_;
    switch (other.TypeCase) {
      case TypeOneofCase.RoomName:
        RoomName = other.RoomName;
        break;
      case TypeOneofCase.Position:
        Position = other.Position;
        break;
      case TypeOneofCase.DisplayName:
        DisplayName = other.DisplayName;
        break;
      case TypeOneofCase.Message:
        Message = other.Message;
        break;
      case TypeOneofCase.NewUserID:
        NewUserID = other.NewUserID;
        break;
      case TypeOneofCase.Event:
        Event = other.Event;
        break;
      case TypeOneofCase.Otoshidama:
        Otoshidama = other.Otoshidama.Clone();
        break;
      case TypeOneofCase.Roulette:
        Roulette = other.Roulette.Clone();
        break;
      case TypeOneofCase.Spaces:
        Spaces = other.Spaces.Clone();
        break;
      case TypeOneofCase.OtoshidamaTotal:
        OtoshidamaTotal = other.OtoshidamaTotal;
        break;
      case TypeOneofCase.Quiz:
        Quiz = other.Quiz.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Data Clone() {
    return new Data(this);
  }

  /// <summary>Field number for the "roomName" field.</summary>
  public const int RoomNameFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string RoomName {
    get { return HasRoomName ? (string) type_ : ""; }
    set {
      type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      typeCase_ = TypeOneofCase.RoomName;
    }
  }
  /// <summary>Gets whether the "roomName" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasRoomName {
    get { return typeCase_ == TypeOneofCase.RoomName; }
  }
  /// <summary> Clears the value of the oneof if it's currently set to "roomName" </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearRoomName() {
    if (HasRoomName) {
      ClearType();
    }
  }

  /// <summary>Field number for the "position" field.</summary>
  public const int PositionFieldNumber = 2;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Position {
    get { return HasPosition ? (int) type_ : 0; }
    set {
      type_ = value;
      typeCase_ = TypeOneofCase.Position;
    }
  }
  /// <summary>Gets whether the "position" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasPosition {
    get { return typeCase_ == TypeOneofCase.Position; }
  }
  /// <summary> Clears the value of the oneof if it's currently set to "position" </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearPosition() {
    if (HasPosition) {
      ClearType();
    }
  }

  /// <summary>Field number for the "DisplayName" field.</summary>
  public const int DisplayNameFieldNumber = 3;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string DisplayName {
    get { return HasDisplayName ? (string) type_ : ""; }
    set {
      type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      typeCase_ = TypeOneofCase.DisplayName;
    }
  }
  /// <summary>Gets whether the "DisplayName" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDisplayName {
    get { return typeCase_ == TypeOneofCase.DisplayName; }
  }
  /// <summary> Clears the value of the oneof if it's currently set to "DisplayName" </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDisplayName() {
    if (HasDisplayName) {
      ClearType();
    }
  }

  /// <summary>Field number for the "message" field.</summary>
  public const int MessageFieldNumber = 4;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Message {
    get { return HasMessage ? (string) type_ : ""; }
    set {
      type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      typeCase_ = TypeOneofCase.Message;
    }
  }
  /// <summary>Gets whether the "message" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasMessage {
    get { return typeCase_ == TypeOneofCase.Message; }
  }
  /// <summary> Clears the value of the oneof if it's currently set to "message" </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearMessage() {
    if (HasMessage) {
      ClearType();
    }
  }

  /// <summary>Field number for the "newUserID" field.</summary>
  public const int NewUserIDFieldNumber = 5;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string NewUserID {
    get { return HasNewUserID ? (string) type_ : ""; }
    set {
      type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      typeCase_ = TypeOneofCase.NewUserID;
    }
  }
  /// <summary>Gets whether the "newUserID" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasNewUserID {
    get { return typeCase_ == TypeOneofCase.NewUserID; }
  }
  /// <summary> Clears the value of the oneof if it's currently set to "newUserID" </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearNewUserID() {
    if (HasNewUserID) {
      ClearType();
    }
  }

  /// <summary>Field number for the "event" field.</summary>
  public const int EventFieldNumber = 7;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Event Event {
    get { return HasEvent ? (global::Event) type_ : global::Event.Roulette; }
    set {
      type_ = value;
      typeCase_ = TypeOneofCase.Event;
    }
  }
  /// <summary>Gets whether the "event" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasEvent {
    get { return typeCase_ == TypeOneofCase.Event; }
  }
  /// <summary> Clears the value of the oneof if it's currently set to "event" </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearEvent() {
    if (HasEvent) {
      ClearType();
    }
  }

  /// <summary>Field number for the "otoshidama" field.</summary>
  public const int OtoshidamaFieldNumber = 8;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Otoshidama Otoshidama {
    get { return typeCase_ == TypeOneofCase.Otoshidama ? (global::Otoshidama) type_ : null; }
    set {
      type_ = value;
      typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.Otoshidama;
    }
  }

  /// <summary>Field number for the "roulette" field.</summary>
  public const int RouletteFieldNumber = 11;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Roulette Roulette {
    get { return typeCase_ == TypeOneofCase.Roulette ? (global::Roulette) type_ : null; }
    set {
      type_ = value;
      typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.Roulette;
    }
  }

  /// <summary>Field number for the "spaces" field.</summary>
  public const int SpacesFieldNumber = 9;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Spaces Spaces {
    get { return typeCase_ == TypeOneofCase.Spaces ? (global::Spaces) type_ : null; }
    set {
      type_ = value;
      typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.Spaces;
    }
  }

  /// <summary>Field number for the "otoshidamaTotal" field.</summary>
  public const int OtoshidamaTotalFieldNumber = 12;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int OtoshidamaTotal {
    get { return HasOtoshidamaTotal ? (int) type_ : 0; }
    set {
      type_ = value;
      typeCase_ = TypeOneofCase.OtoshidamaTotal;
    }
  }
  /// <summary>Gets whether the "otoshidamaTotal" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasOtoshidamaTotal {
    get { return typeCase_ == TypeOneofCase.OtoshidamaTotal; }
  }
  /// <summary> Clears the value of the oneof if it's currently set to "otoshidamaTotal" </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearOtoshidamaTotal() {
    if (HasOtoshidamaTotal) {
      ClearType();
    }
  }

  /// <summary>Field number for the "quiz" field.</summary>
  public const int QuizFieldNumber = 13;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Quiz Quiz {
    get { return typeCase_ == TypeOneofCase.Quiz ? (global::Quiz) type_ : null; }
    set {
      type_ = value;
      typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.Quiz;
    }
  }

  /// <summary>Field number for the "userID" field.</summary>
  public const int UserIDFieldNumber = 6;
  private string userID_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string UserID {
    get { return userID_; }
    set {
      userID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "result" field.</summary>
  public const int ResultFieldNumber = 10;
  private readonly static string ResultDefaultValue = "";

  private string result_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Result {
    get { return result_ ?? ResultDefaultValue; }
    set {
      result_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "result" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasResult {
    get { return result_ != null; }
  }
  /// <summary>Clears the value of the "result" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearResult() {
    result_ = null;
  }

  private object type_;
  /// <summary>Enum of possible cases for the "type" oneof.</summary>
  public enum TypeOneofCase {
    None = 0,
    RoomName = 1,
    Position = 2,
    DisplayName = 3,
    Message = 4,
    NewUserID = 5,
    Event = 7,
    Otoshidama = 8,
    Roulette = 11,
    Spaces = 9,
    OtoshidamaTotal = 12,
    Quiz = 13,
  }
  private TypeOneofCase typeCase_ = TypeOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public TypeOneofCase TypeCase {
    get { return typeCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearType() {
    typeCase_ = TypeOneofCase.None;
    type_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Data);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Data other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (RoomName != other.RoomName) return false;
    if (Position != other.Position) return false;
    if (DisplayName != other.DisplayName) return false;
    if (Message != other.Message) return false;
    if (NewUserID != other.NewUserID) return false;
    if (Event != other.Event) return false;
    if (!object.Equals(Otoshidama, other.Otoshidama)) return false;
    if (!object.Equals(Roulette, other.Roulette)) return false;
    if (!object.Equals(Spaces, other.Spaces)) return false;
    if (OtoshidamaTotal != other.OtoshidamaTotal) return false;
    if (!object.Equals(Quiz, other.Quiz)) return false;
    if (UserID != other.UserID) return false;
    if (Result != other.Result) return false;
    if (TypeCase != other.TypeCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasRoomName) hash ^= RoomName.GetHashCode();
    if (HasPosition) hash ^= Position.GetHashCode();
    if (HasDisplayName) hash ^= DisplayName.GetHashCode();
    if (HasMessage) hash ^= Message.GetHashCode();
    if (HasNewUserID) hash ^= NewUserID.GetHashCode();
    if (HasEvent) hash ^= Event.GetHashCode();
    if (typeCase_ == TypeOneofCase.Otoshidama) hash ^= Otoshidama.GetHashCode();
    if (typeCase_ == TypeOneofCase.Roulette) hash ^= Roulette.GetHashCode();
    if (typeCase_ == TypeOneofCase.Spaces) hash ^= Spaces.GetHashCode();
    if (HasOtoshidamaTotal) hash ^= OtoshidamaTotal.GetHashCode();
    if (typeCase_ == TypeOneofCase.Quiz) hash ^= Quiz.GetHashCode();
    if (UserID.Length != 0) hash ^= UserID.GetHashCode();
    if (HasResult) hash ^= Result.GetHashCode();
    hash ^= (int) typeCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasRoomName) {
      output.WriteRawTag(10);
      output.WriteString(RoomName);
    }
    if (HasPosition) {
      output.WriteRawTag(16);
      output.WriteInt32(Position);
    }
    if (HasDisplayName) {
      output.WriteRawTag(26);
      output.WriteString(DisplayName);
    }
    if (HasMessage) {
      output.WriteRawTag(34);
      output.WriteString(Message);
    }
    if (HasNewUserID) {
      output.WriteRawTag(42);
      output.WriteString(NewUserID);
    }
    if (UserID.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(UserID);
    }
    if (HasEvent) {
      output.WriteRawTag(56);
      output.WriteEnum((int) Event);
    }
    if (typeCase_ == TypeOneofCase.Otoshidama) {
      output.WriteRawTag(66);
      output.WriteMessage(Otoshidama);
    }
    if (typeCase_ == TypeOneofCase.Spaces) {
      output.WriteRawTag(74);
      output.WriteMessage(Spaces);
    }
    if (HasResult) {
      output.WriteRawTag(82);
      output.WriteString(Result);
    }
    if (typeCase_ == TypeOneofCase.Roulette) {
      output.WriteRawTag(90);
      output.WriteMessage(Roulette);
    }
    if (HasOtoshidamaTotal) {
      output.WriteRawTag(96);
      output.WriteInt32(OtoshidamaTotal);
    }
    if (typeCase_ == TypeOneofCase.Quiz) {
      output.WriteRawTag(106);
      output.WriteMessage(Quiz);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasRoomName) {
      output.WriteRawTag(10);
      output.WriteString(RoomName);
    }
    if (HasPosition) {
      output.WriteRawTag(16);
      output.WriteInt32(Position);
    }
    if (HasDisplayName) {
      output.WriteRawTag(26);
      output.WriteString(DisplayName);
    }
    if (HasMessage) {
      output.WriteRawTag(34);
      output.WriteString(Message);
    }
    if (HasNewUserID) {
      output.WriteRawTag(42);
      output.WriteString(NewUserID);
    }
    if (UserID.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(UserID);
    }
    if (HasEvent) {
      output.WriteRawTag(56);
      output.WriteEnum((int) Event);
    }
    if (typeCase_ == TypeOneofCase.Otoshidama) {
      output.WriteRawTag(66);
      output.WriteMessage(Otoshidama);
    }
    if (typeCase_ == TypeOneofCase.Spaces) {
      output.WriteRawTag(74);
      output.WriteMessage(Spaces);
    }
    if (HasResult) {
      output.WriteRawTag(82);
      output.WriteString(Result);
    }
    if (typeCase_ == TypeOneofCase.Roulette) {
      output.WriteRawTag(90);
      output.WriteMessage(Roulette);
    }
    if (HasOtoshidamaTotal) {
      output.WriteRawTag(96);
      output.WriteInt32(OtoshidamaTotal);
    }
    if (typeCase_ == TypeOneofCase.Quiz) {
      output.WriteRawTag(106);
      output.WriteMessage(Quiz);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasRoomName) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(RoomName);
    }
    if (HasPosition) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Position);
    }
    if (HasDisplayName) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DisplayName);
    }
    if (HasMessage) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
    }
    if (HasNewUserID) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(NewUserID);
    }
    if (HasEvent) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Event);
    }
    if (typeCase_ == TypeOneofCase.Otoshidama) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Otoshidama);
    }
    if (typeCase_ == TypeOneofCase.Roulette) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Roulette);
    }
    if (typeCase_ == TypeOneofCase.Spaces) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Spaces);
    }
    if (HasOtoshidamaTotal) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(OtoshidamaTotal);
    }
    if (typeCase_ == TypeOneofCase.Quiz) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Quiz);
    }
    if (UserID.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserID);
    }
    if (HasResult) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Result);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Data other) {
    if (other == null) {
      return;
    }
    if (other.UserID.Length != 0) {
      UserID = other.UserID;
    }
    if (other.HasResult) {
      Result = other.Result;
    }
    switch (other.TypeCase) {
      case TypeOneofCase.RoomName:
        RoomName = other.RoomName;
        break;
      case TypeOneofCase.Position:
        Position = other.Position;
        break;
      case TypeOneofCase.DisplayName:
        DisplayName = other.DisplayName;
        break;
      case TypeOneofCase.Message:
        Message = other.Message;
        break;
      case TypeOneofCase.NewUserID:
        NewUserID = other.NewUserID;
        break;
      case TypeOneofCase.Event:
        Event = other.Event;
        break;
      case TypeOneofCase.Otoshidama:
        if (Otoshidama == null) {
          Otoshidama = new global::Otoshidama();
        }
        Otoshidama.MergeFrom(other.Otoshidama);
        break;
      case TypeOneofCase.Roulette:
        if (Roulette == null) {
          Roulette = new global::Roulette();
        }
        Roulette.MergeFrom(other.Roulette);
        break;
      case TypeOneofCase.Spaces:
        if (Spaces == null) {
          Spaces = new global::Spaces();
        }
        Spaces.MergeFrom(other.Spaces);
        break;
      case TypeOneofCase.OtoshidamaTotal:
        OtoshidamaTotal = other.OtoshidamaTotal;
        break;
      case TypeOneofCase.Quiz:
        if (Quiz == null) {
          Quiz = new global::Quiz();
        }
        Quiz.MergeFrom(other.Quiz);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          RoomName = input.ReadString();
          break;
        }
        case 16: {
          Position = input.ReadInt32();
          break;
        }
        case 26: {
          DisplayName = input.ReadString();
          break;
        }
        case 34: {
          Message = input.ReadString();
          break;
        }
        case 42: {
          NewUserID = input.ReadString();
          break;
        }
        case 50: {
          UserID = input.ReadString();
          break;
        }
        case 56: {
          type_ = input.ReadEnum();
          typeCase_ = TypeOneofCase.Event;
          break;
        }
        case 66: {
          global::Otoshidama subBuilder = new global::Otoshidama();
          if (typeCase_ == TypeOneofCase.Otoshidama) {
            subBuilder.MergeFrom(Otoshidama);
          }
          input.ReadMessage(subBuilder);
          Otoshidama = subBuilder;
          break;
        }
        case 74: {
          global::Spaces subBuilder = new global::Spaces();
          if (typeCase_ == TypeOneofCase.Spaces) {
            subBuilder.MergeFrom(Spaces);
          }
          input.ReadMessage(subBuilder);
          Spaces = subBuilder;
          break;
        }
        case 82: {
          Result = input.ReadString();
          break;
        }
        case 90: {
          global::Roulette subBuilder = new global::Roulette();
          if (typeCase_ == TypeOneofCase.Roulette) {
            subBuilder.MergeFrom(Roulette);
          }
          input.ReadMessage(subBuilder);
          Roulette = subBuilder;
          break;
        }
        case 96: {
          OtoshidamaTotal = input.ReadInt32();
          break;
        }
        case 106: {
          global::Quiz subBuilder = new global::Quiz();
          if (typeCase_ == TypeOneofCase.Quiz) {
            subBuilder.MergeFrom(Quiz);
          }
          input.ReadMessage(subBuilder);
          Quiz = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          RoomName = input.ReadString();
          break;
        }
        case 16: {
          Position = input.ReadInt32();
          break;
        }
        case 26: {
          DisplayName = input.ReadString();
          break;
        }
        case 34: {
          Message = input.ReadString();
          break;
        }
        case 42: {
          NewUserID = input.ReadString();
          break;
        }
        case 50: {
          UserID = input.ReadString();
          break;
        }
        case 56: {
          type_ = input.ReadEnum();
          typeCase_ = TypeOneofCase.Event;
          break;
        }
        case 66: {
          global::Otoshidama subBuilder = new global::Otoshidama();
          if (typeCase_ == TypeOneofCase.Otoshidama) {
            subBuilder.MergeFrom(Otoshidama);
          }
          input.ReadMessage(subBuilder);
          Otoshidama = subBuilder;
          break;
        }
        case 74: {
          global::Spaces subBuilder = new global::Spaces();
          if (typeCase_ == TypeOneofCase.Spaces) {
            subBuilder.MergeFrom(Spaces);
          }
          input.ReadMessage(subBuilder);
          Spaces = subBuilder;
          break;
        }
        case 82: {
          Result = input.ReadString();
          break;
        }
        case 90: {
          global::Roulette subBuilder = new global::Roulette();
          if (typeCase_ == TypeOneofCase.Roulette) {
            subBuilder.MergeFrom(Roulette);
          }
          input.ReadMessage(subBuilder);
          Roulette = subBuilder;
          break;
        }
        case 96: {
          OtoshidamaTotal = input.ReadInt32();
          break;
        }
        case 106: {
          global::Quiz subBuilder = new global::Quiz();
          if (typeCase_ == TypeOneofCase.Quiz) {
            subBuilder.MergeFrom(Quiz);
          }
          input.ReadMessage(subBuilder);
          Quiz = subBuilder;
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Spaces : pb::IMessage<Spaces>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Spaces> _parser = new pb::MessageParser<Spaces>(() => new Spaces());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Spaces> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Spaces() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Spaces(Spaces other) : this() {
    spaces_ = other.spaces_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Spaces Clone() {
    return new Spaces(this);
  }

  /// <summary>Field number for the "spaces" field.</summary>
  public const int Spaces_FieldNumber = 1;
  private static readonly pb::FieldCodec<global::Space> _repeated_spaces_codec
      = pb::FieldCodec.ForEnum(10, x => (int) x, x => (global::Space) x);
  private readonly pbc::RepeatedField<global::Space> spaces_ = new pbc::RepeatedField<global::Space>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Space> Spaces_ {
    get { return spaces_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Spaces);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Spaces other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!spaces_.Equals(other.spaces_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= spaces_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    spaces_.WriteTo(output, _repeated_spaces_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    spaces_.WriteTo(ref output, _repeated_spaces_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += spaces_.CalculateSize(_repeated_spaces_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Spaces other) {
    if (other == null) {
      return;
    }
    spaces_.Add(other.spaces_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10:
        case 8: {
          spaces_.AddEntriesFrom(input, _repeated_spaces_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10:
        case 8: {
          spaces_.AddEntriesFrom(ref input, _repeated_spaces_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Otoshidama : pb::IMessage<Otoshidama>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Otoshidama> _parser = new pb::MessageParser<Otoshidama>(() => new Otoshidama());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Otoshidama> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Otoshidama() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Otoshidama(Otoshidama other) : this() {
    userID_ = other.userID_;
    amount_ = other.amount_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Otoshidama Clone() {
    return new Otoshidama(this);
  }

  /// <summary>Field number for the "userID" field.</summary>
  public const int UserIDFieldNumber = 1;
  private string userID_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string UserID {
    get { return userID_; }
    set {
      userID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "amount" field.</summary>
  public const int AmountFieldNumber = 2;
  private int amount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Amount {
    get { return amount_; }
    set {
      amount_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Otoshidama);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Otoshidama other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (UserID != other.UserID) return false;
    if (Amount != other.Amount) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (UserID.Length != 0) hash ^= UserID.GetHashCode();
    if (Amount != 0) hash ^= Amount.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (UserID.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(UserID);
    }
    if (Amount != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Amount);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (UserID.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(UserID);
    }
    if (Amount != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Amount);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (UserID.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserID);
    }
    if (Amount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Amount);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Otoshidama other) {
    if (other == null) {
      return;
    }
    if (other.UserID.Length != 0) {
      UserID = other.UserID;
    }
    if (other.Amount != 0) {
      Amount = other.Amount;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          UserID = input.ReadString();
          break;
        }
        case 16: {
          Amount = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          UserID = input.ReadString();
          break;
        }
        case 16: {
          Amount = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Roulette : pb::IMessage<Roulette>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Roulette> _parser = new pb::MessageParser<Roulette>(() => new Roulette());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Roulette> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Roulette() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Roulette(Roulette other) : this() {
    userID_ = other.userID_;
    number_ = other.number_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Roulette Clone() {
    return new Roulette(this);
  }

  /// <summary>Field number for the "userID" field.</summary>
  public const int UserIDFieldNumber = 1;
  private string userID_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string UserID {
    get { return userID_; }
    set {
      userID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "number" field.</summary>
  public const int NumberFieldNumber = 2;
  private int number_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Number {
    get { return number_; }
    set {
      number_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Roulette);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Roulette other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (UserID != other.UserID) return false;
    if (Number != other.Number) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (UserID.Length != 0) hash ^= UserID.GetHashCode();
    if (Number != 0) hash ^= Number.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (UserID.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(UserID);
    }
    if (Number != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Number);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (UserID.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(UserID);
    }
    if (Number != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Number);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (UserID.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserID);
    }
    if (Number != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Number);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Roulette other) {
    if (other == null) {
      return;
    }
    if (other.UserID.Length != 0) {
      UserID = other.UserID;
    }
    if (other.Number != 0) {
      Number = other.Number;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          UserID = input.ReadString();
          break;
        }
        case 16: {
          Number = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          UserID = input.ReadString();
          break;
        }
        case 16: {
          Number = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Quiz : pb::IMessage<Quiz>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Quiz> _parser = new pb::MessageParser<Quiz>(() => new Quiz());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Quiz> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Quiz() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Quiz(Quiz other) : this() {
    question_ = other.question_;
    choices_ = other.choices_.Clone();
    answer_ = other.answer_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Quiz Clone() {
    return new Quiz(this);
  }

  /// <summary>Field number for the "question" field.</summary>
  public const int QuestionFieldNumber = 1;
  private string question_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Question {
    get { return question_; }
    set {
      question_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "choices" field.</summary>
  public const int ChoicesFieldNumber = 2;
  private static readonly pb::FieldCodec<string> _repeated_choices_codec
      = pb::FieldCodec.ForString(18);
  private readonly pbc::RepeatedField<string> choices_ = new pbc::RepeatedField<string>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<string> Choices {
    get { return choices_; }
  }

  /// <summary>Field number for the "answer" field.</summary>
  public const int AnswerFieldNumber = 3;
  private int answer_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Answer {
    get { return answer_; }
    set {
      answer_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Quiz);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Quiz other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Question != other.Question) return false;
    if(!choices_.Equals(other.choices_)) return false;
    if (Answer != other.Answer) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Question.Length != 0) hash ^= Question.GetHashCode();
    hash ^= choices_.GetHashCode();
    if (Answer != 0) hash ^= Answer.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Question.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Question);
    }
    choices_.WriteTo(output, _repeated_choices_codec);
    if (Answer != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Answer);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Question.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Question);
    }
    choices_.WriteTo(ref output, _repeated_choices_codec);
    if (Answer != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Answer);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Question.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Question);
    }
    size += choices_.CalculateSize(_repeated_choices_codec);
    if (Answer != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Answer);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Quiz other) {
    if (other == null) {
      return;
    }
    if (other.Question.Length != 0) {
      Question = other.Question;
    }
    choices_.Add(other.choices_);
    if (other.Answer != 0) {
      Answer = other.Answer;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Question = input.ReadString();
          break;
        }
        case 18: {
          choices_.AddEntriesFrom(input, _repeated_choices_codec);
          break;
        }
        case 24: {
          Answer = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Question = input.ReadString();
          break;
        }
        case 18: {
          choices_.AddEntriesFrom(ref input, _repeated_choices_codec);
          break;
        }
        case 24: {
          Answer = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
